### ISSUE TITLE
为什么我跑不到你写论文的结果？大概查1%那么多？

### ISSUE THREAD

**Issue by yuwenxuan3197** [xuanhongrui/KMCLR#5]

**Comment by xuanhongrui** [comment]
结果不同的原因可能有很多，不同的设备，随机的初始化等。下图是我们实验的结果。
<img width="609" alt="1" src="https://user-images.githubusercontent.com/32501419/228838743-14240330-e722-45ef-8449-57a17d39511c.png">
<img width="537" alt="2" src="https://user-images.githubusercontent.com/32501419/228838828-42a75583-f409-470b-9e8c-b189bf252ddb.png">

**Comment by yuwenxuan3197** [comment]
我想问一下这个结果是现在github上公布的结果能跑出来的吗，还是改了部分参数，这个8908是第8908epoch？

**Comment by xuanhongrui** [comment]
原模型，没有修改任何参数，8909是输出的第8909行，只是个标识，无实际意义。8909后面的内容显示正在运行第976个epoch，所以图片中的HR是第975个epoch的结果。
